resolver: lts-8.16

packages: 
  - '.'
  - '../haskell-gettext/'
  - '../text-format-heavy/'

extra-deps: 
  - haskell-gettext-0.1.1.0
  - text-format-heavy-0.1.0.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

