resolver: lts-8.16

packages: 
  - '.'
  - location:
      git: https://github.com/portnov/text-format-heavy.git
      commit: master
    extra-dep: true
  - location:
      git: https://github.com/portnov/haskell-gettext.git
      commit: master
    extra-dep: true

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

